# Generated by Django 4.2.1 on 2023-07-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datafile',
            unique_together=set(),
        ),
    ]
