# Generated by Django 4.2.1 on 2023-07-12 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import loader.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file',
            field=models.FileField(upload_to=loader.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file_mappings',
            field=models.TextField(blank=True),
        ),
    ]
