# Generated by Django 4.2.1 on 2023-07-12 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loader', '0002_project_owner_alter_datafile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datafields', to=settings.AUTH_USER_MODEL),
        ),
    ]
