# Generated by Django 4.2.1 on 2023-05-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('choice', models.CharField(choices=[('DIRECTORY', 'Upload to Current Directory'), ('SQLITE', 'Upload to SQLite'), ('MONGO', 'Upload to MongoDB')], max_length=50)),
            ],
        ),
    ]
