# Generated by Django 4.2.1 on 2023-06-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='file',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title',
        ),
        migrations.AddField(
            model_name='upload',
            name='create_date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='upload',
            name='elapsed_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='upload',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='upload',
            name='file_obj_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='upload',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upload',
            name='file_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='upload',
            name='header',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='upload',
            name='load_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='upload',
            name='memory_consumed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='upload',
            name='start_time',
            field=models.FloatField(default=0.0),
        ),
    ]
